#pragma once
#include <cstddef>
#include <optional>
#include <unordered_map>
#include <vector>

#include "memory/object_pool.hpp"
#include "order.hpp"

/**
 * @brief Price-time-priority matching engine.
 *
 * Each price level holds a FIFO list of individual resting orders, stored as
 * intrusive nodes in an ObjectPool (the list links are pool indices, not
 * pointers, so growing the pool never dangles them). The two sides are sorted
 * vectors of levels: bids descending, asks ascending, so the best price is
 * always front().
 *
 * @par Entry points
 * - place_order:  matching entry point (crosses, then rests the remainder)
 * - cancel_order: O(1) cancel by id via the id->location index
 * - add_order:    rest anonymous liquidity, no matching (seed/benchmark helper)
 * - delete_order: reduce resting volume at a price, FIFO-first
 */
class OrderBook {
public:
    /**
     * @brief Construct an order book.
     * @param capacity Maximum number of simultaneously resting orders.
     */
    explicit OrderBook(std::size_t capacity = 1u << 15);

    /**
     * @brief Place an identified order: cross against the opposite side, then
     *        rest the unfilled remainder according to order.type.
     * @param order The incoming order request.
     * @return The trades generated by matching (empty if nothing executed).
     * TODO: Return vector of trades?
     */
    // [[nodiscard]]
    std::vector<Trade> place_order(const Order& order);

    /**
     * @brief Cancel a previously placed (identified) order in O(1).
     * @param id Identifier of the order to cancel.
     * @note No-op if @p id is unknown or already fully filled.
     */
    void cancel_order(OrderId id);

    /**
     * @brief Rest anonymous liquidity at a price without matching.
     * @param side Book side to add to.
     * @param price Price level.
     * @param volume Quantity to rest; non-positive volume is ignored.
     * @note Kept for book-building and benchmarks; identified flow should use
     *       place_order().
     */
    void add_order(Side side, Price price, Volume volume);

    /**
     * @brief Reduce resting volume at a price, draining whole orders
     * FIFO-first.
     * @param side Book side.
     * @param price Price level to reduce.
     * @param volume Quantity to remove.
     */
    void delete_order(Side side, Price price, Volume volume);

    /**
     * @brief Set the aggregate resting volume at a price to an absolute value.
     *
     * This is the L2 diff-feed primitive: a Binance @c depthUpdate carries the
     * new
     * @em absolute quantity for each touched level, not a delta. Applying one
     * is "set this price to this size", where a size of 0 removes the level.
     * The level is collapsed to a single anonymous aggregate — individual-order
     * identity and FIFO priority are not modelled at L2, so this must not be
     * mixed with place_order()/cancel_order() flow on the same book.
     *
     * @param side Book side to update.
     * @param price Price level to set.
     * @param volume New absolute aggregate volume; <= 0 removes the level.
     * @note O(1) when the level already exists (the common replay case).
     */
    void set_level(Side side, Price price, Volume volume);

    /**
     * @brief Aggregate resting volume at a price on a side.
     * @param price Price level to query.
     * @param side Book side.
     * @return The total resting volume, or 0 if the level does not exist.
     */
    [[nodiscard]] Volume volume_at_price(Price price, Side side) const;

    /// @brief Best (highest) bid price, or std::nullopt if no bids rest.
    [[nodiscard]] std::optional<Price> best_bid() const;

    /// @brief Best (lowest) ask price, or std::nullopt if no asks rest.
    [[nodiscard]] std::optional<Price> best_ask() const;

private:
    /// @brief A resting order living in the pool; FIFO links come from Node<T>.
    struct RestingOrder {
        OrderId id;
        Volume volume;
    };

    using Pool = ObjectPool<RestingOrder>;
    using NodeIndex = Pool::index_type;
    static constexpr NodeIndex kNull = Pool::null_index;

    /// @brief One price level: cached aggregate + head/tail pool indices.
    struct Level {
        Price price;
        Volume total_volume = 0;
        NodeIndex head = kNull; ///< oldest order — fills first
        NodeIndex tail = kNull; ///< newest order — appended here
    };

    /// @brief Where a live order sits, for O(1) cancel.
    struct Location {
        Side side;
        Price price;
        NodeIndex node;
    };

    static constexpr OrderId kAnonymous =
        0; ///< reserved: not tracked in index_

    /**
     * @brief Would an incoming @p side order at @p price trade against a level
     *        resting at @p book_price?
     */
    static bool crosses(Side side, Price price, Price book_price);

    std::vector<Level>& side_levels(Side s);

    [[nodiscard]] const std::vector<Level>& side_levels(Side s) const;

    /**
     * @brief Sorted-position lookup for a level on @p side (bids desc, asks
     * asc).
     *
     * Two overloads so const and non-const callers each get the matching
     * iterator type.
     */
    static std::vector<Level>::iterator find_level(std::vector<Level>& levels,
                                                   Side side, Price price);
    static std::vector<Level>::const_iterator
    find_level(const std::vector<Level>& levels, Side side, Price price);

    /**
     * @brief Cross @p volume against @p opposite, FIFO within each level.
     * @return The unfilled remainder.
     */
    Volume match(OrderId id, Side side, Price price, Volume volume,
                 std::vector<Level>& opposite, std::vector<Trade>& trades);

    /// @brief Append a new order to its side's level FIFO, creating it if
    /// needed.
    void rest(OrderId id, Side side, Price price, Volume volume);

    /// @brief Remove the FIFO head of a level and reclaim its pool slot.
    void pop_front(Level& lvl);

    /// @brief Splice a node out of a level's FIFO without freeing it.
    void unlink(Level& lvl, NodeIndex node);

    /// @brief True if @p volume can be fully filled against @p opposite now.
    [[nodiscard]] bool can_fully_fill(const std::vector<Level>& opposite,
                                      Side side, Price price,
                                      Volume volume) const;

    Pool pool_;
    std::vector<Level> bid_levels_; ///< descending by price (best = front)
    std::vector<Level> ask_levels_; ///< ascending by price (best = front)
    std::unordered_map<OrderId, Location> index_;
};
